#ifndef TAGLIB_TAGLIB_CONFIG_H
#define TAGLIB_TAGLIB_CONFIG_H

#undef TAGLIB_WITH_APE
#undef TAGLIB_WITH_ASF
#undef TAGLIB_WITH_DSF
#undef TAGLIB_WITH_MOD
#undef TAGLIB_WITH_MP4
#undef TAGLIB_WITH_RIFF
#undef TAGLIB_WITH_SHORTEN
#undef TAGLIB_WITH_TRUEAUDIO
#undef TAGLIB_WITH_VORBIS

#endif
